version: '3'

services:
    mongodb:
        image: mongo:5.0
        ports:
            - 27017:27017
        volumes:
            - ~/apps/mongo:/data/db
    parcellab:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        environment:
            - MONGODB=mongodb://host.docker.internal:27017/forecast
            - SERVER_PORT=7001
            - WEATHERAPI=https://api.brightsky.dev
        ports:
            - 7001:7001
        container_name: parcellab
