name: api

on:
    push:
        branches: [main]
        paths:
            - '.github/workflows/workflow.yaml'
            - './**'

    pull_request:
        branches: [main]
        paths:
            - '.github/workflows/workflow.yaml'
            - './**'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: yarn install
            - name: Run integration tests
              run: yarn test:integration
            - name: Run unit tests
              run: yarn test:unit
